version: '3.8'

services:
  # Servicio de la Base de Datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: nextprof_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nextprof_secure_pwd
      POSTGRES_DB: nextprof_db
    ports:
      - "5432:5432" # Expuesto a localhost para que te conectes con TablePlus
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Servicio de la Aplicación Web Next.js
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextprof_web
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:nextprof_secure_pwd@db:5432/nextprof_db
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
