import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';

const url = process.env.PLANS_TEST_DATABASE_URL;
test('plan configuration, quota recovery, documents and API limits persist atomically', { skip: !url }, async t => {
  const target = new URL(url!);
  assert.ok(['127.0.0.1', 'localhost', '[::1]'].includes(target.hostname) && target.pathname.includes('test'), 'An isolated local test database is required');
  process.env.DATABASE_URL = url;
  const { db, pool } = await import('@/db');
  const schema = await import('@/db/schema');
  const { users, cvs, aiJobs, usagePeriods, usageOperations, monetizationAssignments, monetizationEvents, planConfigs, planConfigHistory, auditLogs, userApiTokens } = schema;
  const { eq, and, inArray, sql } = await import('drizzle-orm');
  const usage = await import('@/lib/usage');
  const cv = await import('@/lib/cv-access');
  const { getPlanConfig } = await import('@/lib/plan-store');
  const { publishPlanConfig } = await import('@/lib/plan-admin');
  const { consumeApiPlanRate } = await import('@/lib/api-plan-rate');
  const tokens = await import('@/lib/agent-api/tokens');
  const guestPdf = await import('@/lib/guest-pdf');
  const { createTrySourceCv } = await import('@/lib/try-cv');
  const fixtures: string[] = [];
  const user = async (values: Partial<typeof users.$inferInsert> = {}) => {
    const id = randomUUID(); fixtures.push(id);
    await db.insert(users).values({ id, email: `plans-${id}@example.test`, ...values }); return id;
  };
  const reserve = (id: string, requestId: string = randomUUID(), input: unknown = { fixture: true }, units = 1) => usage.beginUsage(id, { bucket: 'general', requestId, action: 'test', input, units });
  const original = await getPlanConfig();
  const admin = await user({ role: 'admin' });
  try {
    await t.test('one last CV slot is shared across concurrent creations', async () => {
      const id = await user();
      await cv.createCvForUser(id, { title: 'Base', content: 'Base', isBase: true });
      await cv.createCvForUser(id, { title: 'Version', content: 'Version', isBase: false });
      const results = await Promise.allSettled([1, 2].map(n => cv.createCvForUser(id, { title: `Version ${n}`, content: 'Content', isBase: false })));
      assert.equal(results.filter(r => r.status === 'fulfilled').length, 1);
      assert.equal((results.find(r => r.status === 'rejected') as PromiseRejectedResult).reason.code, 'CV_LIMIT');
      assert.equal((await cv.getCvAccess(id)).total, 3);
      await assert.rejects(cv.createCvForUser(id, { title: 'Second base', content: 'Base', isBase: true }), e => (e as any).code === 'CV_LIMIT');
    });
    await t.test('a deleted base leaves room for one new manual source while both adapted versions are retained', async () => {
      const id = await user();
      const base = await cv.createManualCvForUser(id, { title: 'Base', content: 'Source' });
      assert.equal(base.isBase, true); assert.equal(base.isPrincipal, true);
      const one = await cv.createCvForUser(id, { title: 'Version one', content: 'Adapted one', isBase: false });
      const two = await cv.createCvForUser(id, { title: 'Version two', content: 'Adapted two', isBase: false });
      await db.delete(cvs).where(eq(cvs.id, base.id));
      const attempts = await Promise.allSettled([1, 2].map(n => cv.createManualCvForUser(id, { title: `New base ${n}`, content: 'New source' })));
      assert.equal(attempts.filter(item => item.status === 'fulfilled').length, 1);
      const created = (attempts.find(item => item.status === 'fulfilled') as PromiseFulfilledResult<typeof base>).value;
      assert.equal(created.isBase, true);
      assert.equal((attempts.find(item => item.status === 'rejected') as PromiseRejectedResult).reason.code, 'CV_LIMIT');
      const access = await cv.getCvAccess(id);
      assert.equal(access.total, 3); assert.equal(access.baseCvId, created.id);
      assert.ok(access.activeIds.includes(one.id) && access.activeIds.includes(two.id));
    });
    await t.test('the demo source CV replays double clicks, rejects incompatible input or owner and does not consume AI', async () => {
      const id = await user({ isGuest: true }), other = await user({ isGuest: true });
      const input = { id: randomUUID(), title: 'Demo source', content: '# Candidate\n\nExperience with React.' };
      const [one, two] = await Promise.all([createTrySourceCv(id, input), createTrySourceCv(id, { ...input })]);
      assert.equal(one, input.id); assert.equal(two, one);
      const access = await cv.getCvAccess(id);
      assert.equal(access.total, 1); assert.equal(access.baseCvId, one); assert.equal(access.cvs[0].isBase, true);
      assert.deepEqual((await usage.getUsageSnapshot(id)).usage.general, { used: 0, reserved: 0, limit: 10, remaining: 10, resetAt: null });
      await assert.rejects(createTrySourceCv(id, { ...input, content: 'Different input' }), error => (error as any).code === 'OPERATION_CONFLICT');
      await assert.rejects(createTrySourceCv(other, input), error => (error as any).code === 'OPERATION_CONFLICT');
      await assert.rejects(createTrySourceCv(id, { ...input, id: randomUUID() }), error => (error as any).code === 'CV_LIMIT');
      assert.equal((await cv.getCvAccess(other)).total, 0);
    });
    await t.test('untrusted resume patches cannot change ownership, reservation, identity or admission categories', async () => {
      const id = await user(), recipient = await user();
      const base = await cv.createCvForUser(id, { title: 'Base', content: 'Base', isBase: true });
      for (const patch of [{ userId: recipient }, { id: randomUUID() }, { pendingUsageOperationId: randomUUID() }, { createdAt: new Date(0) }, { updatedAt: new Date(0) }]) {
        await assert.rejects(cv.updateCvForUser(id, base.id, patch), e => (e as any).code === 'INVALID_CV_PATCH');
      }
      await assert.rejects(cv.createCvForUser(id, { title: 'Invalid category', content: '', isBase: 'false' as any }), e => (e as any).code === 'INVALID_CV_TYPE');
      const [saved] = await db.select().from(cvs).where(eq(cvs.id, base.id));
      assert.equal(saved.userId, id); assert.equal(saved.pendingUsageOperationId, null); assert.equal(saved.isBase, true);
      assert.equal((await cv.getCvAccess(recipient)).total, 0);
    });
    await t.test('downgrade preserves all CVs, selects recent versions, rejects direct writes and allows reselection', async () => {
      const id = await user({ subscriptionStatus: 'active' });
      const base = await cv.createCvForUser(id, { title: 'Base', content: 'Original', isBase: true, isPrincipal: true });
      const versions = [];
      for (let i = 0; i < 4; i++) versions.push(await cv.createCvForUser(id, { title: `Version ${i}`, content: `Saved ${i}`, isBase: false, isPrincipal: i === 0, updatedAt: new Date(2026, 0, i + 1) }));
      await db.update(users).set({ subscriptionStatus: 'canceled' }).where(eq(users.id, id));
      let access = await cv.getCvAccess(id);
      assert.deepEqual(new Set(access.activeIds), new Set([base.id, versions[3].id, versions[2].id]));
      assert.equal(access.total, 5);
      await assert.rejects(cv.updateCvForUser(id, versions[0].id, { content: 'overwrite' }), e => (e as any).code === 'CV_READ_ONLY');
      await assert.rejects(cv.createCvForUser(id, { title: 'Extra', content: 'Extra' }), e => (e as any).code === 'CV_LIMIT');
      access = await cv.selectActiveCvs(id, base.id, [versions[0].id, versions[1].id]);
      assert.ok(access.activeIds.includes(versions[0].id));
      await cv.updateCvForUser(id, versions[0].id, { content: 'Edited selection' });
      const [retained] = await db.select({ content: cvs.content }).from(cvs).where(eq(cvs.id, versions[3].id)); assert.equal(retained.content, 'Saved 3');
      await db.update(users).set({ subscriptionStatus: 'active' }).where(eq(users.id, id));
      assert.equal((await cv.getCvAccess(id)).readOnlyIds.length, 0);
    });
    await t.test('confirmed replacement preserves original until publication; cancellation releases capacity', async () => {
      const id = await user();
      const base = await cv.createCvForUser(id, { title: 'Base', content: 'Base', isBase: true });
      const adapted = await cv.createCvForUser(id, { title: 'Version', content: 'Previous', isBase: false });
      const operation = await reserve(id);
      await assert.rejects(db.transaction(tx => cv.reserveCvTarget(tx, id, { baseCvId: base.id, targetCvId: adapted.id, operationId: operation.id, values: { isBase: false } })), e => (e as any).code === 'CV_OVERWRITE_CONFIRM');
      await db.transaction(tx => cv.reserveCvTarget(tx, id, { targetCvId: adapted.id, confirmOverwrite: true, operationId: operation.id, values: { isBase: false } }));
      await assert.rejects(cv.updateCvForUser(id, adapted.id, { content: 'Manual race' }), e => (e as any).code === 'OPERATION_IN_PROGRESS');
      await db.transaction(tx => usage.releaseUsage(tx, operation.id));
      const [retained] = await db.select({ content: cvs.content, pending: cvs.pendingUsageOperationId }).from(cvs).where(eq(cvs.id, adapted.id));
      assert.deepEqual(retained, { content: 'Previous', pending: null });
      const next = await reserve(id);
      const emptyId = await db.transaction(tx => cv.reserveCvTarget(tx, id, { operationId: next.id, values: { title: 'Pending', isBase: false } }));
      await db.update(usageOperations).set({ expiresAt: new Date(0) }).where(eq(usageOperations.id, next.id));
      await usage.reconcileUsage();
      assert.equal((await db.select().from(cvs).where(eq(cvs.id, emptyId))).length, 0);
      assert.equal((await usage.getUsageSnapshot(id)).usage.general.reserved, 0);
    });
    await t.test('queued jobs cannot starve cleanup of expired synchronous reservations', async () => {
      const id = await user({ subscriptionStatus: 'active' });
      const [{ id: periodId }] = await db.insert(usagePeriods).values({ userId: id, bucket: 'general', periodStart: usage.utcUsageMonth(), reserved: 101 }).returning({ id: usagePeriods.id });
      const jobIds = Array.from({ length: 101 }, () => randomUUID());
      await db.insert(aiJobs).values(jobIds.map(jobId => ({ id: jobId, userId: id, kind: 'import_offer', status: 'queued', payload: {} })));
      await db.insert(usageOperations).values(jobIds.map(jobId => ({ userId: id, periodId, bucket: 'general', requestId: randomUUID(), action: 'cleanup_fixture', inputHash: usage.usageInputHash({ jobId }), units: 1,
        configVersion: original.version, plan: 'pro', jobId, expiresAt: new Date(0) })));
      const stale = await reserve(id);
      await db.update(usageOperations).set({ expiresAt: new Date(1) }).where(eq(usageOperations.id, stale.id));
      await usage.reconcileUsage();
      const [released] = await db.select().from(usageOperations).where(eq(usageOperations.id, stale.id));
      assert.equal(released.status, 'released');
      assert.equal((await usage.getUsageSnapshot(id)).usage.general.reserved, 101);
    });
    await t.test('the one demo PDF is reserved atomically; render failures release it and legacy downloads still count', async () => {
      const id = await user({ isGuest: true });
      const cvId = randomUUID();
      const attempts = await Promise.allSettled([guestPdf.beginGuestPdfDownload(id, cvId), guestPdf.beginGuestPdfDownload(id, cvId)]);
      assert.equal(attempts.filter(item => item.status === 'fulfilled').length, 1);
      assert.equal((attempts.find(item => item.status === 'rejected') as PromiseRejectedResult).reason.code, 'GUEST_DOWNLOAD_LIMIT');
      const held = (attempts.find(item => item.status === 'fulfilled') as PromiseFulfilledResult<Awaited<ReturnType<typeof guestPdf.beginGuestPdfDownload>>>).value;
      assert.equal(await guestPdf.guestHasPdfDownloadRemaining(id), false);
      assert.equal(await guestPdf.countGuestPdfDownloads(id), 0);
      await guestPdf.releaseGuestPdfDownload(held.id);
      assert.equal(await guestPdf.guestHasPdfDownloadRemaining(id), true);
      const replacement = await guestPdf.beginGuestPdfDownload(id, cvId);
      await guestPdf.completeGuestPdfDownload(replacement, null, { cvId });
      assert.equal(await guestPdf.countGuestPdfDownloads(id), 1);
      await assert.rejects(guestPdf.beginGuestPdfDownload(id, cvId), error => (error as any).code === 'GUEST_DOWNLOAD_LIMIT');
      await assert.rejects(guestPdf.completeGuestPdfDownload(replacement, null, { cvId }), error => (error as any).code === 'OPERATION_RELEASED');
      assert.equal(await guestPdf.countGuestPdfDownloads(id), 1);
      const legacy = await user({ isGuest: true });
      await db.insert(auditLogs).values({ userId: legacy, action: guestPdf.GUEST_PDF_DOWNLOAD_ACTION, details: '{}' });
      await assert.rejects(guestPdf.beginGuestPdfDownload(legacy, cvId), error => (error as any).code === 'GUEST_DOWNLOAD_LIMIT');
      const interrupted = await user({ isGuest: true });
      const abandoned = await guestPdf.beginGuestPdfDownload(interrupted, cvId);
      await db.update(usageOperations).set({ expiresAt: new Date(0) }).where(eq(usageOperations.id, abandoned.id));
      assert.equal(await guestPdf.guestHasPdfDownloadRemaining(interrupted), true);
      const recovered = await guestPdf.beginGuestPdfDownload(interrupted, cvId);
      await guestPdf.completeGuestPdfDownload(recovered, null, { cvId });
      const [expired] = await db.select().from(usageOperations).where(eq(usageOperations.id, abandoned.id));
      assert.equal(expired.status, 'released');
    });
    await t.test('a PDF admitted in the demo completes after registration without losing its reservation', async () => {
      const guest = await user({ isGuest: true }), registered = await user();
      const cvId = randomUUID(), operation = await guestPdf.beginGuestPdfDownload(guest, cvId);
      await db.transaction(tx => usage.transferGuestUsage(tx, guest, registered));
      await db.delete(users).where(eq(users.id, guest));
      await guestPdf.completeGuestPdfDownload(operation, null, { cvId });
      assert.equal(await guestPdf.countGuestPdfDownloads(registered), 1);
      const [saved] = await db.select().from(usageOperations).where(eq(usageOperations.id, operation.id));
      assert.equal(saved.userId, registered); assert.equal(saved.status, 'consumed');
    });
    await t.test('repeated IDs recover the saved result, incompatible input conflicts and reservations cannot be revived', async () => {
      const id = await user(), requestId = randomUUID();
      const operation = await reserve(id, requestId, { a: 1, b: 2 });
      await assert.rejects(reserve(id, requestId, { b: 2, a: 1 }), e => (e as any).code === 'OPERATION_IN_PROGRESS');
      await assert.rejects(reserve(id, requestId, { a: 2, b: 2 }), e => (e as any).code === 'OPERATION_CONFLICT');
      await db.transaction(tx => usage.consumeUsage(tx, operation.id, { answer: 'durable' }));
      const replay = await reserve(id, requestId, { b: 2, a: 1 });
      assert.deepEqual(replay.result, { answer: 'durable' });
      await db.transaction(tx => usage.consumeUsage(tx, operation.id, { answer: 'double-click' }));
      assert.equal((await usage.getUsageSnapshot(id)).usage.general.used, 1);
      const pending = await reserve(id);
      await db.transaction(tx => usage.releaseUsage(tx, pending.id));
      await assert.rejects(reserve(id, pending.requestId), e => (e as any).code === 'OPERATION_RELEASED');
    });
    await t.test('month rollover settles into the admitted period; new month starts without carry', async () => {
      const id = await user(); const operation = await reserve(id);
      const previous = usage.utcUsageMonth(); previous.setUTCMonth(previous.getUTCMonth() - 1);
      await db.update(usagePeriods).set({ periodStart: previous }).where(eq(usagePeriods.id, operation.periodId));
      await db.transaction(tx => usage.consumeUsage(tx, operation.id, { saved: true }));
      assert.equal((await usage.getUsageSnapshot(id)).usage.general.used, 0);
      const fresh = await reserve(id, randomUUID(), { month: 'new' }, 10);
      await db.transaction(tx => usage.consumeUsage(tx, fresh.id, { saved: true }));
      assert.equal((await usage.getUsageSnapshot(id)).usage.general.used, 10);
      const [old] = await db.select().from(usagePeriods).where(eq(usagePeriods.id, operation.periodId)); assert.equal(old.used, 1);
    });
    await t.test('guest claim retains consumption, pending jobs, exposure and first value without resetting', async () => {
      const guest = await user({ isGuest: true, firstValueAt: new Date() }), registered = await user();
      const used = await reserve(guest, randomUUID(), { demo: true }, 8);
      await db.transaction(tx => usage.consumeUsage(tx, used.id, { result: true }));
      const pending = await reserve(guest);
      await db.insert(monetizationAssignments).values({ userId: guest, experimentVersion: 1, variant: 'b', firstExposedAt: new Date() });
      await db.insert(monetizationEvents).values({ userId: guest, experimentVersion: 1, variant: 'b', event: 'paywall_view', source: 'test' });
      await db.transaction(tx => usage.transferGuestUsage(tx, guest, registered));
      const snapshot = await usage.getUsageSnapshot(registered);
      assert.equal(snapshot.usage.general.used, 8); assert.equal(snapshot.usage.general.reserved, 1); assert.equal(snapshot.usage.general.remaining, 1);
      const [claimed] = await db.select().from(usageOperations).where(eq(usageOperations.id, pending.id)); assert.equal(claimed.userId, registered);
      await db.transaction(tx => usage.consumeUsage(tx, claimed.id, { recovered: true }));
      assert.equal((await usage.getUsageSnapshot(registered)).usage.general.used, 9);
      const [assignment] = await db.select().from(monetizationAssignments).where(eq(monetizationAssignments.userId, registered)); assert.equal(assignment.variant, 'b'); assert.ok(assignment.firstExposedAt);
      const [owner] = await db.select({ first: users.firstValueAt }).from(users).where(eq(users.id, registered)); assert.ok(owner.first);
      assert.equal((await db.select().from(monetizationEvents).where(eq(monetizationEvents.userId, registered))).length, 1);
    });
    await t.test('API keys are hashed once, concurrent creation respects capacity, rate limits aggregate and survive new calls', async () => {
      const id = await user({ subscriptionStatus: 'active' });
      const attempts = await Promise.allSettled([0, 1, 2, 3].map(n => tokens.createUserApiToken(id, `Key ${n}`, ['cv:read'])));
      assert.equal(attempts.filter(r => r.status === 'fulfilled').length, 3);
      const keys = await db.select().from(userApiTokens).where(eq(userApiTokens.userId, id)); assert.equal(keys.length, 3);
      assert.ok(keys.every(key => key.tokenHash.length === 64 && key.tokenCipher === null));
      assert.ok((await tokens.listUserApiTokens(id)).every(key => key.recoverable === false));
      await assert.rejects(tokens.revealUserApiToken(id, keys[0].id), e => (e as any).code === 'token_unavailable');
      const minute = new Date('2026-10-04T20:00:30.000Z');
      const requests = await Promise.allSettled(Array.from({ length: 61 }, () => consumeApiPlanRate(id, minute)));
      assert.equal(requests.filter(r => r.status === 'fulfilled').length, 60);
      assert.equal((requests.find(r => r.status === 'rejected') as PromiseRejectedResult).reason.code, 'rate_limited');
      await assert.rejects(consumeApiPlanRate(id, minute), e => (e as any).code === 'rate_limited');
      await consumeApiPlanRate(id, new Date(minute.getTime() + 60_000));
    });
    await t.test('admin publication detects conflicts, records history and changes new admissions without resetting usage', async () => {
      const id = await user(); const held = await reserve(id, randomUUID(), { capacity: true }, 10);
      const before = await getPlanConfig(); const changed = structuredClone(before); changed.free.generalAiMonthly = 1;
      const requests = await Promise.allSettled([publishPlanConfig(admin, { expectedVersion: before.version, config: changed }), publishPlanConfig(admin, { expectedVersion: before.version, config: changed })]);
      assert.equal(requests.filter(r => r.status === 'fulfilled').length, 1);
      assert.match((requests.find(r => r.status === 'rejected') as PromiseRejectedResult).reason.message, /PLAN_CONFIG_CONFLICT/);
      await assert.rejects(reserve(id), e => (e as any).code === 'QUOTA_EXCEEDED');
      await db.transaction(tx => usage.consumeUsage(tx, held.id, { admitted: true }));
      assert.equal((await usage.getUsageSnapshot(id)).usage.general.used, 10);
      assert.equal((await usage.getUsageSnapshot(id)).usage.general.remaining, 0);
      const current = await getPlanConfig();
      const restored = await publishPlanConfig(admin, { expectedVersion: current.version, config: { ...before, version: current.version } });
      assert.equal(restored.free.generalAiMonthly, 10); assert.equal((await usage.getUsageSnapshot(id)).usage.general.used, 10);
      const [history] = await db.select().from(planConfigHistory).where(eq(planConfigHistory.version, restored.version)); assert.equal(history.updatedByUserId, admin);
      const logs = await db.select().from(auditLogs).where(and(eq(auditLogs.userId, admin), eq(auditLogs.action, 'admin_plan_config_save'))); assert.equal(logs.length, 2);
      await assert.rejects(publishPlanConfig(id, { expectedVersion: restored.version, config: restored }), /ADMIN_REQUIRED/);
      await assert.rejects(publishPlanConfig(admin, { expectedVersion: restored.version, config: restored }, { supportSessionId: randomUUID() }), /ADMIN_IMPERSONATION_FORBIDDEN/);
    });
    await t.test('default-copy repair publishes once, preserves customized translations and never resets usage', async () => {
      const id = await user();
      const charged = await reserve(id, randomUUID(), { repairFixture: true }, 3);
      await db.transaction(tx => usage.consumeUsage(tx, charged.id, { saved: true }));
      const before = await getPlanConfig(), legacy = structuredClone(before);
      legacy.paywall.copy.a.es.body = 'Conserva esta candidatura y prepara la siguiente. PRO incluye versiones de CV sin límite y {generalAiMonthly} acciones de IA al mes.';
      legacy.paywall.copy.a.en.body = 'Customized administrator copy with {maxCvs} resumes.';
      await db.update(planConfigs).set({ config: legacy }).where(eq(planConfigs.id, 1));
      const migration = await readFile(new URL('../drizzle/0036_dynamic_default_paywall.sql', import.meta.url), 'utf8');
      await db.execute(sql.raw(migration));
      const repaired = await getPlanConfig();
      assert.equal(repaired.version, before.version + 1);
      assert.equal(repaired.paywall.experimentVersion, before.paywall.experimentVersion + 1);
      assert.match(repaired.paywall.copy.a.es.body, /\{maxCvs\}/);
      assert.equal(repaired.paywall.copy.a.en.body, legacy.paywall.copy.a.en.body);
      const [history] = await db.select().from(planConfigHistory).where(eq(planConfigHistory.version, repaired.version));
      assert.equal(history.updatedByUserId, null); assert.deepEqual(history.config, repaired);
      assert.equal((await usage.getUsageSnapshot(id)).usage.general.used, 3);
      await db.execute(sql.raw(migration));
      assert.equal((await getPlanConfig()).version, repaired.version);
      assert.equal((await usage.getUsageSnapshot(id)).usage.general.used, 3);
    });
  } finally {
    const current = await getPlanConfig();
    // This database is dedicated to the suite; restore the defaults without touching application data.
    await db.update(planConfigs).set({ config: { ...original, version: current.version } }).where(eq(planConfigs.id, 1));
    await db.delete(users).where(inArray(users.id, fixtures)); await pool.end();
  }
});
