'use client';
import { InlineAllowance } from '@/components/subscription/InlineAllowance';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { readAdviceAction, acceptFollowupAction } from '@/app/dashboard/applications/people/actions';
import type { listAdvice } from '@/lib/people/context';
import type { listThreads, personLinks } from '@/lib/people/service';
import type { NetworkingAction } from '@/lib/people/types';
import type { NetworkingJobControl } from './useNetworkingJob';
import { control, Field, panel, errorLabel, usePeopleText } from './ui';

export default function Assistant({ personId, threads, links, threadId, setThread, job, revision }: { personId: string; threads: Awaited<ReturnType<typeof listThreads>>; links: Awaited<ReturnType<typeof personLinks>>; threadId: string; setThread: (id: string) => void; job: NetworkingJobControl; revision: number }) {
  const tx = usePeopleText(), en = tx('es', 'en') === 'en', router = useRouter();
  const [offerId, setOffer] = useState(''), [includeCandidate, setInclude] = useState(false), [results, setResults] = useState<Awaited<ReturnType<typeof listAdvice>>>([]), [error, setError] = useState(''), [copied, setCopied] = useState(''), [accepting, setAccepting] = useState('');
  useEffect(() => { let active = true; void readAdviceAction(personId).then(r => { if (active) { if (r.error) setError(r.error); else setResults(r.data!); } }).catch(() => { if (active) setError('PEOPLE_ACTION_FAILED'); }); return () => { active = false; }; }, [personId, revision, links]);
  const actions: Array<{ key: NetworkingAction; es: string; en: string; desc: string; descEn: string }> = [
    { key: 'first_contact', es: 'Preparar primer contacto', en: 'Prepare first contact', desc: 'Tres aperturas, un gancho y una pregunta concreta.', descEn: 'Three openings, a hook and a specific question.' },
    { key: 'reply', es: 'Proponer respuesta', en: 'Suggest a reply', desc: 'Continuar desde el último intercambio confirmado.', descEn: 'Continue from the latest confirmed exchange.' },
    { key: 'conversation_prep', es: 'Preparar conversación', en: 'Prepare conversation', desc: 'Temas y preguntas para una llamada o encuentro.', descEn: 'Topics and questions for a call or meeting.' },
    { key: 'next_step', es: 'Recomendar próximo paso', en: 'Recommend next step', desc: 'Qué aportar, qué preguntar y cuándo retomar el contacto.', descEn: 'What to offer, what to ask and when to follow up.' },
  ];
  return <div className="space-y-6"><section className={`${panel} space-y-4`}><h2 className="font-display text-lg font-semibold text-text">{tx('Contexto del asistente', 'Assistant context')}</h2><p className="text-sm text-text-muted">{tx('La IA usa el perfil y sus vínculos. Elige un hilo y una oferta para concretar la recomendación. El CV es opcional.', 'AI uses the profile and its relationships. Select a thread and offer to focus the recommendation. A CV is optional.')}</p><div className="grid sm:grid-cols-2 gap-4"><Field label={tx('Hilo confirmado', 'Confirmed thread')}><select className={control} value={threadId} onChange={e => setThread(e.target.value)}><option value="">{tx('Sin conversación', 'No conversation')}</option>{threads.map(t => <option key={t.id} value={t.id}>{t.title} · {t.channel}</option>)}</select></Field><Field label={tx('Oferta vinculada', 'Linked offer')}><select className={control} value={offerId} onChange={e => setOffer(e.target.value)}><option value="">{tx('Sin oferta', 'No offer')}</option>{links.offers.map(o => <option key={o.offerId} value={o.offerId}>{o.title} · {o.company}</option>)}</select></Field></div><label className="flex gap-2 items-center text-sm text-text"><input type="checkbox" checked={includeCandidate} onChange={e => setInclude(e.target.checked)} />{tx('Incluir mi perfil profesional y CV base, si existen', 'Include my career profile and base CV, if available')}</label></section>
    <InlineAllowance />
    <div className="grid sm:grid-cols-2 gap-4">{actions.map(a => <section key={a.key} className={`${panel} space-y-3`}><h3 className="font-display font-semibold text-text">{tx(a.es, a.en)}</h3><p className="text-sm text-text-muted">{tx(a.desc, a.descEn)}</p><Button variant="ai" disabled={job.busy || (a.key === 'reply' && !threadId)} onClick={() => job.start(a.key, { threadId: threadId || undefined, offerId: offerId || undefined, includeCandidate })}><Sparkles className="h-4 w-4" />{tx('Generar', 'Generate')}</Button></section>)}</div>
    {results.map(result => <article key={result.id} className={`${panel} space-y-5`}><div className="flex flex-wrap justify-between gap-3"><h2 className="font-display text-lg font-semibold text-text">{tx(actions.find(a => a.key === result.action)?.es || 'Recomendación', actions.find(a => a.key === result.action)?.en || 'Recommendation')}</h2><span className="text-xs text-text-muted">{new Date(result.createdAt).toLocaleString(en ? 'en-GB' : 'es-ES')}</span></div>{result.stale && <p role="status" className="rounded-[8px] bg-surface-muted p-3 text-sm text-text">{tx('Desactualizado: el contexto ha cambiado desde esta generación.', 'Outdated: the context changed since this was generated.')}</p>}
    <p className="text-xs text-text-muted break-words">{tx('Contexto utilizado', 'Context used')}: {tx('perfil y vínculos', 'profile and relationships')}{result.context.threadId ? ` · ${threads.find(t => t.id === result.context.threadId)?.title || tx('hilo eliminado', 'deleted thread')}` : ''}{result.context.offerId ? ` · ${links.offers.find(o => o.offerId === result.context.offerId)?.title || tx('oferta desvinculada', 'unlinked offer')}` : ''}{result.context.includeCandidate ? ` · ${tx('perfil y CV del candidato', 'candidate profile and CV')}` : ''}</p>
    {result.advice.drafts.map((d, i) => <section key={i} className="border border-ai/20 rounded-[10px] p-4 bg-ai/5 space-y-3"><h3 className="font-semibold text-text">{d.title}</h3><p className="whitespace-pre-wrap break-words text-sm text-text">{d.text}</p><Button variant="secondary" size="sm" onClick={async () => { try { await navigator.clipboard.writeText(d.text); setCopied(`${result.id}:${i}`); } catch { setError('PEOPLE_ACTION_FAILED'); } }}>{copied === `${result.id}:${i}` ? tx('Copiado', 'Copied') : tx('Copiar borrador', 'Copy draft')}</Button></section>)}
    {(['facts', 'hypotheses', 'recommendations', 'hooks', 'questions'] as const).map(key => result.advice[key].length ? <section key={key}><h3 className="text-sm font-semibold text-text">{({ facts: tx('Hechos', 'Facts'), hypotheses: tx('Hipótesis', 'Hypotheses'), recommendations: tx('Recomendaciones', 'Recommendations'), hooks: tx('Ganchos', 'Hooks'), questions: tx('Preguntas', 'Questions') })[key]}</h3><ul className="list-disc pl-5 text-sm text-text-muted mt-2 space-y-1">{result.advice[key].map((v, i) => <li key={i}>{v}</li>)}</ul></section> : null)}
    {result.advice.nextAction && <section className="border-t border-subtle pt-4 space-y-3"><h3 className="font-semibold text-text">{tx('Próxima acción propuesta', 'Suggested next action')}</h3><p className="text-sm text-text">{result.advice.nextAction}</p>{result.advice.followupDate && <p className="text-sm text-text-muted">{tx('Fecha', 'Date')}: {result.advice.followupDate}</p>}<Button variant="strong" loading={accepting === result.id} disabled={result.stale || !!accepting} onClick={async () => { setAccepting(result.id); setError(''); try { const r = await acceptFollowupAction(personId, result.id); if (r.error) setError(r.error); else router.refresh(); } catch { setError('PEOPLE_ACTION_FAILED'); } finally { setAccepting(''); } }}>{tx('Confirmar seguimiento', 'Confirm follow-up')}</Button></section>}
    </article>)}
    {error && <p role="alert" className="text-sm text-danger">{errorLabel(error, en)}</p>}
  </div>;
}
