'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/Button';
import * as actions from '@/app/dashboard/applications/people/actions';
import type { listThreads, readConversation, getImport } from '@/lib/people/service';
import { CONVERSATION_CHANNELS, CONVERSATION_MAX, type MessageInput, type ProposedMessage } from '@/lib/people/types';
import type { NetworkingJobControl } from './useNetworkingJob';
import { control, Field, panel, errorLabel, usePeopleText } from './ui';

type Review = Awaited<ReturnType<typeof getImport>>;
export default function Conversations({ personId, name, threads, threadId, setThread, job, revision }: { personId: string; name: string; threads: Awaited<ReturnType<typeof listThreads>>; threadId: string; setThread: (id: string) => void; job: NetworkingJobControl; revision: number }) {
  const tx = usePeopleText(), en = tx('es', 'en') === 'en', router = useRouter();
  const [history, setHistory] = useState<Awaited<ReturnType<typeof readConversation>> | null>(null), [error, setError] = useState(''), [busy, setBusy] = useState(false), [title, setTitle] = useState(''), [channel, setChannel] = useState('linkedin'), [raw, setRaw] = useState(''), [review, setReview] = useState<Review | null>(null), [proposed, setProposed] = useState<Array<ProposedMessage & { selected: boolean }>>([]), [refresh, setRefresh] = useState(0), [message, setMessage] = useState<MessageInput>({ author: 'self', content: '', sentAt: null }), [editingId, setEditing] = useState<string | undefined>(), [copied, setCopied] = useState(false);
  useEffect(() => { let active = true; setHistory(null); setReview(null); if (threadId) void actions.readThreadAction(personId, threadId).then(r => { if (active) { if (r.error) setError(r.error); else { setHistory(r.data!); const ready = r.data?.imports.find(item => item.status === 'review'); if (ready) void actions.readImportAction(personId, ready.id).then(item => { if (active && item.data) { setReview(item.data); setProposed(item.data.proposed.map(m => ({ ...m, selected: !m.overlap }))); } }); } } }).catch(() => { if (active) setError('PEOPLE_ACTION_FAILED'); }); return () => { active = false; }; }, [personId, threadId, refresh, revision]);
  async function perform<T>(fn: () => Promise<{ error?: string; data?: T }>, done?: (value: T) => void) { setBusy(true); setError(''); try { const r = await fn(); if (r.error) setError(r.error); else { if (done) done(r.data!); setRefresh(v => v + 1); router.refresh(); } } catch { setError('PEOPLE_ACTION_FAILED'); } finally { setBusy(false); } }
  async function openImport(importId: string) { setBusy(true); setError(''); try { const r = await actions.readImportAction(personId, importId); if (r.error) setError(r.error); else if (r.data) { setReview(r.data); setProposed(r.data.proposed.map(m => ({ ...m, selected: !m.overlap }))); } } catch { setError('PEOPLE_ACTION_FAILED'); } finally { setBusy(false); } }
  const author = (value: string) => value === 'self' ? tx('Tú', 'You') : value === 'contact' ? name : tx('Autor por revisar', 'Author to review');
  const edit = (i: number, patch: Partial<ProposedMessage & { selected: boolean }>) => setProposed(list => list.map((m, n) => n === i ? { ...m, ...patch } : m));
  return <div className="space-y-6">
    <section className={`${panel} space-y-4`}><h2 className="font-display text-lg font-semibold text-text">{tx('Hilos de conversación', 'Conversation threads')}</h2><Field label={tx('Hilo seleccionado', 'Selected thread')}><select className={control} value={threadId} onChange={e => setThread(e.target.value)}><option value="">{tx('Selecciona un hilo', 'Select a thread')}</option>{threads.map(t => <option key={t.id} value={t.id}>{t.title} · {t.channel}</option>)}</select></Field>
    <form className="flex flex-wrap gap-3 items-end" onSubmit={e => { e.preventDefault(); void perform(() => actions.createThreadAction(personId, title, channel), t => { setThread(t.id); setTitle(''); }); }}><div className="flex-1 min-w-[150px]"><Field label={tx('Nuevo hilo', 'New thread')}><input className={control} required maxLength={180} value={title} onChange={e => setTitle(e.target.value)} /></Field></div><Field label={tx('Canal', 'Channel')}><select className={control} value={channel} onChange={e => setChannel(e.target.value)}>{CONVERSATION_CHANNELS.map(c => <option key={c} value={c}>{c === 'other' ? tx('Otro', 'Other') : c === 'linkedin' ? 'LinkedIn' : 'Email'}</option>)}</select></Field><Button type="submit" loading={busy}>{tx('Crear hilo', 'Create thread')}</Button></form></section>
    {threadId && <>
      <section className={`${panel} space-y-4`}><h2 className="font-display text-lg font-semibold text-text">{tx('Importar conversación', 'Import conversation')}</h2><p className="text-sm text-text-muted">{tx('Pega el texto completo. Guardaremos el original; revisarás autores, fechas y coincidencias antes de incorporar mensajes.', 'Paste the full text. We save the original; review authors, dates and overlaps before adding messages.')}</p><Field label={tx('Texto original', 'Original text')}><textarea className={control} rows={7} value={raw} onChange={e => setRaw(e.target.value)} /></Field><p className={`text-xs ${raw.length > CONVERSATION_MAX ? 'text-danger' : 'text-text-muted'}`}>{raw.length.toLocaleString()} / 120.000 {tx('caracteres', 'characters')}</p>
      {raw.length > CONVERSATION_MAX && <p role="alert" className="text-sm text-danger">{errorLabel('PEOPLE_CONVERSATION_SIZE', en)}</p>}
      <Button variant="ai" loading={busy || job.busy} disabled={!raw.trim() || raw.length > CONVERSATION_MAX} onClick={() => perform(() => actions.saveImportAction(personId, threadId, raw), record => { if (record.status === 'pending') void job.start('parse_conversation', { threadId, importId: record.id }); else void openImport(record.id); })}>{tx('Guardar y preparar revisión con IA', 'Save and prepare AI review')}</Button>
      {history?.imports.length ? <details><summary className="cursor-pointer text-sm text-text">{tx('Originales e importaciones guardadas', 'Saved originals and imports')} ({history.imports.length})</summary><ul className="space-y-2 mt-3">{history.imports.map(r => <li key={r.id} className="flex flex-wrap gap-3 items-center"><span className="text-sm text-text-muted">{new Date(r.createdAt).toLocaleString(en ? 'en-GB' : 'es-ES')} · {r.status === 'confirmed' ? tx('Confirmada', 'Confirmed') : r.status === 'review' ? tx('Por revisar', 'Review ready') : tx('Pendiente', 'Pending')}</span><Button size="sm" variant="ghost" onClick={() => openImport(r.id)}>{tx('Abrir', 'Open')}</Button></li>)}</ul></details> : null}</section>
      {review && <section className={`${panel} space-y-4`}><h2 className="font-display text-lg font-semibold text-text">{tx('Revisar importación', 'Review import')}</h2><details><summary className="text-sm text-text cursor-pointer">{tx('Consultar texto original', 'View original text')}</summary><pre className="whitespace-pre-wrap break-words text-sm text-text mt-3">{review.rawText}</pre></details>
      {review.status === 'confirmed' ? <p className="text-sm text-text-muted">{tx('Esta importación ya está confirmada. No añadiremos mensajes otra vez.', 'This import is confirmed. Messages will not be added again.')}</p> : review.status === 'pending' ? <Button variant="ai" disabled={job.busy} onClick={() => job.start('parse_conversation', { threadId: review.threadId, importId: review.id })}>{tx('Preparar revisión / reintentar', 'Prepare review / retry')}</Button> : <>
        <p className="text-sm text-text-muted">{tx('Las coincidencias aparecen desmarcadas para revisión. Revisa los autores y las fechas inciertas. Dos mensajes iguales pueden ser legítimos.', 'Overlaps are unchecked for review. Check uncertain authors and dates. Identical messages may be legitimate.')}</p>
        {proposed.map((m, i) => <div key={i} className="border border-subtle rounded-[8px] p-3 space-y-3"><label className="flex gap-2 items-center text-sm text-text"><input type="checkbox" checked={m.selected} onChange={e => edit(i, { selected: e.target.checked })} />{tx('Incorporar mensaje', 'Include message')} {i + 1}</label>{(m.overlap || m.uncertain) && <p className="text-xs text-text-muted">{m.overlap ? tx('Posible solapamiento', 'Possible overlap') : tx('Autor o fecha por revisar', 'Author or date to review')}</p>}<div className="grid sm:grid-cols-2 gap-3"><Field label={tx('Autor', 'Author')}><select className={control} value={m.author} onChange={e => edit(i, { author: e.target.value as MessageInput['author'] })}>{['self', 'contact', 'unknown'].map(a => <option key={a} value={a}>{author(a)}</option>)}</select></Field><Field label={tx('Fecha (opcional)', 'Date (optional)')}><input type="date" className={control} value={m.sentAt?.slice(0, 10) || ''} onChange={e => edit(i, { sentAt: e.target.value || null })} /></Field></div><Field label={tx('Contenido literal editable', 'Editable literal content')}><textarea className={control} rows={3} value={m.content} onChange={e => edit(i, { content: e.target.value })} /></Field></div>)}
        <Button variant="strong" loading={busy} onClick={() => perform(() => actions.confirmImportAction(personId, review.id, proposed.filter(m => m.selected).map(({ author, content, sentAt }) => ({ author, content, sentAt }))), () => setReview(null))}>{tx('Confirmar mensajes seleccionados', 'Confirm selected messages')} ({proposed.filter(m => m.selected).length})</Button>
      </>}</section>}
      <section className={`${panel} space-y-4`}><div className="flex flex-wrap justify-between gap-3"><h2 className="font-display text-lg font-semibold text-text">{tx('Historial confirmado', 'Confirmed history')}</h2><Button variant="secondary" size="sm" disabled={!history?.messages.length} onClick={async () => { try { await navigator.clipboard.writeText(history!.messages.map(m => `${author(m.author)}${m.sentAt ? ` · ${new Date(m.sentAt).toLocaleString()}` : ''}\n${m.content}`).join('\n\n')); setCopied(true); } catch { setError('PEOPLE_ACTION_FAILED'); } }}>{copied ? tx('Copiado', 'Copied') : tx('Copiar historial', 'Copy history')}</Button></div>
      {!history ? <p role="status" className="text-sm text-text-muted">{tx('Cargando…', 'Loading…')}</p> : !history.messages.length ? <p className="text-sm text-text-muted">{tx('Todavía no hay mensajes confirmados.', 'No confirmed messages yet.')}</p> : <ol className="space-y-3">{history.messages.map(m => <li key={m.id} className={`rounded-[10px] p-4 border border-subtle ${m.author === 'self' ? 'bg-ai/5 sm:ml-12' : 'bg-surface-muted/50 sm:mr-12'}`}><p className="text-xs text-text-muted mb-2">{author(m.author)}{m.sentAt ? ` · ${new Date(m.sentAt).toLocaleString(en ? 'en-GB' : 'es-ES')}` : ''}</p><p className="whitespace-pre-wrap break-words text-sm text-text">{m.content}</p><div className="flex gap-2 mt-3"><Button variant="ghost" size="sm" onClick={() => { setEditing(m.id); setMessage({ author: m.author as MessageInput['author'], content: m.content, sentAt: m.sentAt?.toISOString() || null }); }}>{tx('Corregir', 'Edit')}</Button><Button variant="ghost" size="sm" disabled={busy} onClick={() => { if (window.confirm(tx('¿Eliminar este mensaje?', 'Delete this message?'))) void perform(() => actions.deleteMessageAction(personId, m.id)); }}>{tx('Eliminar', 'Delete')}</Button></div></li>)}</ol>}
      <form className="border-t border-subtle pt-4 space-y-3" onSubmit={e => { e.preventDefault(); void perform(() => actions.saveMessageAction(personId, threadId, message, editingId), () => { setEditing(undefined); setMessage({ author: 'self', content: '', sentAt: null }); }); }}><h3 className="font-semibold text-text">{editingId ? tx('Corregir mensaje', 'Edit message') : tx('Añadir mensaje manualmente', 'Add message manually')}</h3><div className="grid sm:grid-cols-2 gap-3"><Field label={tx('Autor', 'Author')}><select className={control} value={message.author} onChange={e => setMessage(m => ({ ...m, author: e.target.value as MessageInput['author'] }))}>{['self', 'contact', 'unknown'].map(a => <option key={a} value={a}>{author(a)}</option>)}</select></Field><Field label={tx('Fecha (opcional)', 'Date (optional)')}><input className={control} type="date" value={message.sentAt?.slice(0, 10) || ''} onChange={e => setMessage(m => ({ ...m, sentAt: e.target.value || null }))} /></Field></div><Field label={tx('Mensaje', 'Message')}><textarea className={control} required maxLength={120000} rows={4} value={message.content} onChange={e => setMessage(m => ({ ...m, content: e.target.value }))} /></Field><div className="flex gap-3"><Button type="submit" variant="strong" loading={busy}>{tx('Guardar mensaje', 'Save message')}</Button>{editingId && <Button type="button" variant="ghost" onClick={() => { setEditing(undefined); setMessage({ author: 'self', content: '', sentAt: null }); }}>{tx('Cancelar', 'Cancel')}</Button>}</div></form>
      </section>
    </>}
    {error && <p role="alert" className="text-sm text-danger">{errorLabel(error, en)}</p>}
  </div>;
}
